<th scope="col">RPU</th>
<th scope="col"><i class="fa-solid fa-list-check"></i></th>
<th scope="col">CUENTA</th>
<th scope="col">CICLO</th>
<th scope="col">TARIFA</th>
<th scope="col">MOTIVO MANUAL</th>
<!-- <th scope="col">SIN USO</th> -->
<th scope="col">LECTURA MANUAL</th>
<th scope="col">KWH A RECUPERAR</th>
<th scope="col">RESPALDO</th>
<th scope="col">ORDEN SERVICIO</th>
<th scope="col">RPE_AUXILIAR</th>
<th scope="col">OBSERVACIONES</th>
<!-- <th scope="col">CORRECCION</th> -->
<th scope="col">AGENCIA</th>
<th scope="col">RESPONSABLE_MANUAL</th>
<th scope="col">FECHA</th>
<th scope="col">MODIFICÓ</th>
<th scope="col">MOTIVO MODIFICACIÓN</th>
<th scope="col">ACCION</th>